import { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function Landing() {
  const nav = useNavigate();
  const [name, setName] = useState("Government Planner");
  const [role, setRole] = useState("Solar Planning Cell");

  return (
    <div className="hero">
      <div className="hero-left">
        <h1>
          SolarSphere AI
          <br />
          Government Solar Planning
        </h1>
        <p>
          Feature 3 takes rooftop-level solar assessment results generated by Feature 1 for
          multiple locations, aggregates them geographically, calculates locality and
          city-level solar potential, visualizes it through GIS, and provides budget-based
          planning scenarios, environmental impact, and an AI-assisted government planning
          report.
        </p>
        <div className="hero-points">
          <div className="hero-point">
            <i>1</i>
            <span>
              Feature 1 rooftop outputs → locality and city-level solar intelligence
            </span>
          </div>
          <div className="hero-point">
            <i>2</i>
            <span>Explainable Solar Potential Index (0–100) with full factor breakdown</span>
          </div>
          <div className="hero-point">
            <i>3</i>
            <span>Budget simulation, scenario comparison and CO₂ impact estimation</span>
          </div>
          <div className="hero-point">
            <i>4</i>
            <span>AI planning assistant grounded in the dataset, calculations and documents</span>
          </div>
        </div>
        <div className="pill-row">
          <span className="pill">
            <b>Input</b> Feature 1 Excel output
          </span>
          <span className="pill">
            <b>Aggregation</b> Locality → City
          </span>
          <span className="pill">
            <b>Output</b> Planning dashboard, map, scenarios, PDF report
          </span>
        </div>
      </div>

      <div className="hero-right">
        <div className="login-box">
          <h3>Planning Console Access</h3>
          <div className="hint">
            Demonstration login — no credentials are verified. This session is used to
            identify the planner in generated reports.
          </div>
          <label>Planner name</label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Your name"
          />
          <label>Department / cell</label>
          <input
            type="text"
            value={role}
            onChange={(e) => setRole(e.target.value)}
            placeholder="Department"
          />
          <button
            className="btn"
            onClick={() => {
              sessionStorage.setItem(
                "solarsphere_user",
                JSON.stringify({ name, role }),
              );
              nav("/dashboard");
            }}
          >
            Enter planning dashboard
          </button>
        </div>
      </div>
    </div>
  );
}
